version: '3.9'
services:
  process-app:
    container_name: process-app
    build:
      context: .
      dockerfile: ./process-app/docker/Dockerfile
    volumes:
      - ./process-app:/process-app
      - /process-app/node_modules/
    depends_on:
      - db
    command: ["/process-app/docker/wait-for-it.sh", "db:5432", "--", "npm", "run", "start"]
  db:
    container_name: db
    image: postgres:latest
    volumes:
    - ./db/seeds/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: domains
      POSTGRES_USER: adblaster
      POSTGRES_PASSWORD: nX^M3^eLY%DG#JePc6nd
networks:
  adblaster:
    name: adblaster